import { Component,Input } from '@angular/core';

@Component({
  selector: 'app-minecraft-base',
  templateUrl: './minecraft-base.component.html',
  styleUrls: ['./minecraft-base.component.css']
})
export class MinecraftBaseComponent {
    @Input() corso: string | undefined;
  clienti = [
    { 
        pagamento: 'Pagato', 
        partecipante: 'Mario Rossi', 
        eta: 35, 
        genitore: 'Giovanni Rossi', 
        mailCliente: 'mario.rossi@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5555', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Luca Verdi', 
        eta: 28, 
        genitore: 'Alessio Verdi', 
        mailCliente: 'luca.verdi@example.com', 
        newsletter: 'No', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'Sì', 
        cellulare: '555-555-5556', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Anna Bianchi', 
        eta: 42, 
        genitore: 'Luigi Bianchi', 
        mailCliente: 'anna.bianchi@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'No', 
        ritiro: 'No', 
        cellulare: '555-555-5557', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Sofia Gialli', 
        eta: 10, 
        genitore: 'Paolo Gialli', 
        mailCliente: 'sofia.gialli@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'No', 
        privacy: 'No', 
        ritiro: 'Sì', 
        cellulare: '555-555-5558', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Antonio Viola', 
        eta: 56, 
        genitore: 'Maria Viola', 
        mailCliente: 'antonio.viola@example.com', 
        newsletter: 'No', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5559', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Elena Marroni', 
        eta: 19, 
        genitore: 'Giuseppe Marroni', 
        mailCliente: 'elena.marroni@example.com', 
        newsletter: 'No', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5560', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Roberto Rossi', 
        eta: 38, 
        genitore: 'Giovanni Rossi', 
        mailCliente: 'roberto.rossi@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5561', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Silvia Verdi', 
        eta: 31, 
        genitore: 'Alessio Verdi', 
        mailCliente: 'silvia.verdi@example.com', 
        newsletter: 'No', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'Sì', 
        cellulare: '555-555-5562', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Laura Bianchi', 
        eta: 47, 
        genitore: 'Luigi Bianchi', 
        mailCliente: 'laura.bianchi@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'No', 
        ritiro: 'No', 
        cellulare: '555-555-5563', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Giuseppe Gialli', 
        eta: 14, 
        genitore: 'Paolo Gialli', 
        mailCliente: 'giuseppe.gialli@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'No', 
        privacy: 'No', 
        ritiro: 'Sì', 
        cellulare: '555-555-5564', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Maria Viola', 
        eta: 52, 
        genitore: 'Maria Viola', 
        mailCliente: 'maria.viola@example.com', 
        newsletter: 'No', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5565', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    },
    { 
        pagamento: 'Non Pagato', 
        partecipante: 'Giovanni Azzurro', 
        eta: 40, 
        genitore: 'Mario Azzurro', 
        mailCliente: 'giovanni.azzurro@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'Sì', 
        privacy: 'Sì', 
        ritiro: 'No', 
        cellulare: '555-555-5566', 
        note: 'Nessuna nota', 
        legenda: 'Standard' 
    },
    { 
        pagamento: 'Pagato', 
        partecipante: 'Elisa Gialli', 
        eta: 23, 
        genitore: 'Paolo Gialli', 
        mailCliente: 'elisa.gialli@example.com', 
        newsletter: 'Sì', 
        allergie: 'Nessuna', 
        liberatoria: 'No', 
        privacy: 'No', 
        ritiro: 'Sì', 
        cellulare: '555-555-5567', 
        note: 'Nessuna nota', 
        legenda: 'Premium' 
    }
];


}
